version: 2

jobs:
  bionic_gcc7_coverage:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - checkout
      - run:
          name: Build and test
          command: >-
            git submodule update --init --recursive
            bash ./tools/circleci_bionic_gcc7_coverage.sh

  bionic_clang6_release:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - checkout
      - run:
          name: Build and test
          command: >-
            git submodule update --init --recursive
            bash ./tools/circleci_bionic_clang6_release.sh

#  macosx_xcode_11_release:
#    macos:
#      xcode: "11.3.0"
#    steps:
#      - checkout
#      - run:
#          name: Build and test
#          command: >-
#            git submodule update --init --recursive
#            bash ./tools/circleci_macosx_xcode_11_release.sh

workflows:
  version: 2
  all_builds:
    jobs:
      - bionic_gcc7_coverage
      - bionic_clang6_release
#      - macosx_xcode_11_release
